Repository githubschool/june-5, pull requests merged in 2018-06, with the labels that each got.

#15 Rbrauer braai food
  braai-food.md
Labels: AwesomeFood

#12 create file with technologies in nagsmandya,tech
  tech.md
Labels: enhancement

#14 Create Integration.mb
  Integration.mb
Labels: bug

#9 create file with restaurants in olathe, ks
  olathe-restaurants.md
Labels: enhancement

#10 Create recent books read by ChrissieG9
  recentbooksread.md
Labels: books_enhancement

#16 Create file with Initial list of Computer Games
  gaming.md
Labels: enhancement
